apiVersion: v1
kind: Service
metadata:
  name: consul
spec:
  ports:
    - port: 8500
      targetPort: 8500
      name: http
  selector:
    app: consul
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
spec:
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: consul:1.15.4
          args: ["agent", "-dev", "-client=0.0.0.0"]
          ports:
            - containerPort: 8500
          readinessProbe:
            exec:
              command: ["consul", "members"]
            initialDelaySeconds: 10
            periodSeconds: 10