apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  kong.yml: |
    # Your Kong configuration here
---
apiVersion: v1
kind: Service
metadata:
  name: kong
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      name: proxy
    - port: 8443
      targetPort: 8443
      name: proxy-ssl
    - port: 8001
      targetPort: 8001
      name: admin
  selector:
    app: kong
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
spec:
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: kong:latest
          env:
            - name: KONG_PROXY_LISTEN
              value: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
            - name: KONG_ADMIN_LISTEN
              value: "0.0.0.0:8001"
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: "/etc/kong/kong.yml"
          ports:
            - containerPort: 8000
            - containerPort: 8443
            - containerPort: 8001
          volumeMounts:
            - name: kong-config
              mountPath: /etc/kong
          readinessProbe:
            exec:
              command: ["kong", "health"]
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: kong-config
          configMap:
            name: kong-config