apiVersion: v1
kind: Service
metadata:
  name: postfix
spec:
  ports:
    - port: 25
      targetPort: 25
  selector:
    app: postfix
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix
spec:
  selector:
    matchLabels:
      app: postfix
  template:
    metadata:
      labels:
        app: postfix
    spec:
      containers:
        - name: postfix
          image: quay.io/panubo/postfix:latest
          env:
            - name: MAILNAME
              value: "localhost"
            - name: RELAYHOST_AUTH
              value: "no"
            - name: SMTP_TLS_SECURITY_LEVEL
              value: "may"
          ports:
            - containerPort: 25
          readinessProbe:
            tcpSocket:
              port: 25
            initialDelaySeconds: 10
            periodSeconds: 10