apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\anass\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yml --out k8s
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: consul
  name: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consul
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\anass\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yml --out k8s
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: consul
    spec:
      containers:
        - args:
            - agent
            - -dev
            - -client=0.0.0.0
          image: consul:1.15.4
          livenessProbe:
            exec:
              command:
                - consul
                - members
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: consul
          ports:
            - containerPort: 8500
              protocol: TCP
      restartPolicy: Always
