apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\anass\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yml --out k8s
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: payment-service
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: payment-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\anass\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yml --out k8s
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: payment-service
    spec:
      containers:
        - env:
            - name: CONSUL_HOST
              value: consul
            - name: CONSUL_PORT
              value: "8500"
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@payment-db:5432/transport_payment
            - name: KONG_ADMIN_URL
              value: http://kong:8001
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3003"
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq:5672
            - name: SERVICE_NAME
              value: payment-service
          image: payment-service
          name: payment-service
          ports:
            - containerPort: 3003
              protocol: TCP
      restartPolicy: Always
