apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\anass\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yml --out k8s
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: payment-db
  name: payment-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: payment-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\anass\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yml --out k8s
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: payment-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: transport_payment
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: postgres:16-alpine
          livenessProbe:
            exec:
              command:
                - pg_isready -U postgres
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: payment-db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: payment-db-data
      restartPolicy: Always
      volumes:
        - name: payment-db-data
          persistentVolumeClaim:
            claimName: payment-db-data
