apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\anass\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yml --out k8s
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: postfix
  name: postfix
spec:
  ports:
    - name: "25"
      port: 25
      targetPort: 25
  selector:
    io.kompose.service: postfix
