apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\anass\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yml --out k8s
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: postfix
  name: postfix
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postfix
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\anass\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yml --out k8s
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: postfix
    spec:
      containers:
        - env:
            - name: MAILNAME
              value: localhost
            - name: RELAYHOST
            - name: RELAYHOST_AUTH
              value: "no"
            - name: SMTP_TLS_SECURITY_LEVEL
              value: may
          image: quay.io/panubo/postfix:latest
          name: postfix
          ports:
            - containerPort: 25
              protocol: TCP
      restartPolicy: Always
